import sqlite3
conn = sqlite3.connect('instance/restaurant_dev.db')
cursor = conn.cursor()
cursor.execute('UPDATE orders SET status = "processing" WHERE status = "preparing"')
print(f'Fixed {cursor.rowcount} orders with preparing status')
cursor.execute('UPDATE orders SET status = "processing" WHERE status = "ready"')
print(f'Fixed {cursor.rowcount} orders with ready status')
conn.commit()
conn.close()
print('Database fix completed')
